export interface Theme {
    '--theme-switch-notch': string,
    '--theme-switch-bg': string,
    '--logo-color': string,
    '--card-color': string,
    '--background': string,
    '--gray-line': string,
    '--text': string,
    '--text-highlight': string,
    '--title': string,
    '--red': string,
    '--purple': string,
    '--green': string,
    '--green-positive': string,
    '--blue': string,
    '--blue-dark': string,
    '--blue-twitter': string,
    '--accent': string,
    '--accent-soft': string,
    '--accent-gold': string,
    '--accent-mint': string,
    '--card-border': string,
    '--shadow-color': string,
    'background': string,
}
